#%RAML 1.0
title: Advanced REST Client Echo service API
version: v1
baseUri: http://localhost:{port}/{version}
mediaType: [application/json]

baseUriParameters:
  port:
    type: integer
    default: 8080
    examples:
      Default: 8080
      Demo: 8081
traits:
  RequestResponse:
    responses:
      200:
        body:
          application/json:
            description: |
              Successful response returns request data as a JSON object.
            type: RequestDataResponse
types:
  BaseResponse:
    type: object
    properties:
      success:
        type: boolean
        description: Wherther or not the operation succeeded.
  AuthorizationResponse:
    type: BaseResponse
    properties:
      authorized:
        type: boolean
        description: Wherther or not the user is authenticated.
  CookieList: !include types/cookies-list.raml
  RequestDataResponse: !include types/request-data-response.raml
  CookieListResponse: [BaseResponse, CookieList]

securitySchemes:
  oauth2:
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization: string
      responses:
        401:
          description: Authentication failed
    settings:
      accessTokenUri: https://auth.domain.com/token
      authorizationUri: https://auth.domain.com/auth
      authorizationGrants: [authorization_code, implicit]
      scopes: [profile, email]
  basic:
    type: Basic Authentication
    describedBy:
      responses:
        401:
          description: Authentication failed

/:
  get:
    responses:
      200:
        body:
          type: CookieListResponse
  post:
    body:
      type: object
      properties:
        test?: boolean
/auth/basic:
  securedBy: [basic]
  get:
    responses:
      200:
        body:
          type: CookieListResponse
